{
    parserClass="com.techern.dlang.parsing.DParser"

    extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

    psiClassPrefix="D"
    psiImplClassSuffix="Impl"
    psiPackage="com.techern.dlang.parsing"
    psiImplPackage="com.techern.dlang.parsing.impl"

    elementTypeHolderClass="com.techern.dlang.parsing.DTypes"
    elementTypeClass="com.techern.dlang.parsing.DElementType"
    tokenTypeClass="com.techern.dlang.parsing.DTokenType"
}

pLeftCurly ::= "{"
pRightCurly ::= "}"

pLeftSquare ::= "["
pRightSquare ::= "]"

pLeft ::= "("
pRight ::= ")"

pAnyLeft ::= pLeftCurly | pLeftSquare | pLeft
pAnyRight ::= pRightCurly | pRightSquare | pRight
pAny ::= pAnyLeft | pAnyRight //If you use this, you are weird.
